### PR TITLE
hello excuse me this is just hurts my eyes

### PR DESCRIPTION
**Pull request by d1snin**

### CODE REVIEW

**Review by 5HT2 — CHANGES_REQUESTED** [review]
I don't know why you're making this change... the note is indented because it's related to the above note

**Comment by d1snin** [comment]
meh It doesn't look like that

**Comment by d1snin** [comment]
maybe do something like...

- [ ] Switch to a different prominent color library, because the current one doesn't support webp
|
    - [ ] Switch to webp for saving images

**Comment by 5HT2** [comment]
It's not up to me how markdown looks on github

**Pull request closed without merging**
